[
    {
        "alwaysOnTop": false,
        "focused": true,
        "height": 840,
        "id": 1878079469,
        "incognito": false,
        "left": -8,
        "state": "maximized",
        "tabs": [
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.youtube.com/s/desktop/45ea6c88/img/logos/favicon_32x32.png",
                "frozen": false,
                "groupId": -1,
                "height": 737,
                "highlighted": false,
                "id": 1878080195,
                "incognito": false,
                "index": 0,
                "lastAccessed": 1755838657979.985,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "(16565) $500 vs $5,000 vs $50,000 Websites (With Examples) - YouTube",
                "url": "https://www.youtube.com/watch?v=GFTDR8_q63M",
                "width": 1047,
                "windowId": 1878079469
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.youtube.com/s/desktop/45ea6c88/img/logos/favicon_32x32.png",
                "frozen": false,
                "groupId": -1,
                "height": 737,
                "highlighted": false,
                "id": 1878080340,
                "incognito": false,
                "index": 1,
                "lastAccessed": 1755838661888.794,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "(16565) Apps so simple you won’t believe they make money - YouTube",
                "url": "https://www.youtube.com/watch?v=iLxGvLTDv3s",
                "width": 1047,
                "windowId": 1878079469
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.youtube.com/s/desktop/45ea6c88/img/logos/favicon_32x32.png",
                "frozen": false,
                "groupId": -1,
                "height": 737,
                "highlighted": false,
                "id": 1878080308,
                "incognito": false,
                "index": 2,
                "lastAccessed": 1755841655283.434,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "(16565) Learn Prompt Engineering: Full Beginner Crash Course (5 HOURS!) - YouTube",
                "url": "https://www.youtube.com/watch?v=LWiMwhDZ9as&list=PL2HX_yT71umB_oqitnmDgYSKltddPfZ-k&index=5",
                "width": 947,
                "windowId": 1878079469
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://cdn.oaistatic.com/assets/favicon-l4nq08hd.svg",
                "frozen": false,
                "groupId": -1,
                "height": 737,
                "highlighted": false,
                "id": 1878080368,
                "incognito": false,
                "index": 3,
                "lastAccessed": 1755846282326.414,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Complete design update",
                "url": "https://chatgpt.com/c/68a812c8-64c0-832a-ae21-dbf291608bf4",
                "width": 1536,
                "windowId": 1878079469
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://developer.mozilla.org/favicon.svg",
                "frozen": false,
                "groupId": -1,
                "height": 737,
                "highlighted": false,
                "id": 1878080397,
                "incognito": false,
                "index": 4,
                "lastAccessed": 1755845843366.223,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "theme",
                "url": "https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme",
                "width": 1536,
                "windowId": 1878079469
            },
            {
                "active": true,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "",
                "frozen": false,
                "groupId": -1,
                "height": 737,
                "highlighted": true,
                "id": 1878080413,
                "incognito": false,
                "index": 5,
                "lastAccessed": 1755846360437.345,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": true,
                "status": "complete",
                "title": "Extensions",
                "url": "chrome://extensions/",
                "width": 1536,
                "windowId": 1878079469
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "chrome-extension://edacconmaakjimmfgnblocblbcdcpbko/favicon.ico",
                "frozen": false,
                "groupId": -1,
                "height": 737,
                "highlighted": false,
                "id": 1878080484,
                "incognito": false,
                "index": 6,
                "lastAccessed": 1755846046533.784,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Session Buddy",
                "url": "chrome-extension://edacconmaakjimmfgnblocblbcdcpbko/session-buddy.html",
                "width": 1536,
                "windowId": 1878079469
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://c1.tablecdn.com/iconbuddy/svgicons-favicon.png",
                "frozen": false,
                "groupId": -1,
                "height": 737,
                "highlighted": false,
                "id": 1878080581,
                "incognito": false,
                "index": 7,
                "lastAccessed": 1755846212297.07,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Search results for \"close\" - Free SVG Icons",
                "url": "https://freesvgicons.com/search?q=close",
                "width": 1536,
                "windowId": 1878079469
            }
        ],
        "top": -8,
        "type": "normal",
        "width": 1552
    },
    {
        "alwaysOnTop": false,
        "focused": false,
        "height": 740,
        "id": 1878080375,
        "incognito": false,
        "left": 46,
        "state": "minimized",
        "tabs": [
            {
                "active": true,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://frontendmasters.com/favicon-32x32.png",
                "frozen": false,
                "groupId": -1,
                "height": 646,
                "highlighted": true,
                "id": 1878080226,
                "incognito": false,
                "index": 0,
                "lastAccessed": 1755840738144.213,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": true,
                "status": "complete",
                "title": "Complete Intro to Computer Science Course by Brian Holt | FEM | Frontend Masters",
                "url": "https://frontendmasters.com/courses/computer-science-v2/",
                "width": 1440,
                "windowId": 1878080375
            }
        ],
        "top": 92,
        "type": "normal",
        "width": 1455
    }
]